export const ancestralTraits = [
  ['Dauntless', 'Manifest Destiny', 'Mixed Heritage', 'Mountain Amongst Men',
    'Natural Selection', 'Blessing in Disguise', 'Danger Sense', 'Esoteric Memory',
    'Grim Resolve', 'Seventh Sense', 'Fortune\'s wheel', 'Noble Savage',],
  ['Cavesight', 'Children of the Earth', 'Consume Alcohol', 'Dwarven Warfare',
    'Grudgebearer', 'Ironclad', 'Oathkeeper', 'Physical Prowess', 'Rune-marked Glory',
    'Stentorian Voice', 'Stoneheaded', 'Strength of the Mountain',],
  ['Bewitching', 'Beyond the Veil', 'Deadly Aim', 'Enduring Mortality', 
    'Fey Treachery', 'Firstborn', 'Kindred Warband', 'Lament of the Ages',
    'Meditative Healing', 'Nature\'s own', 'Nighteyes', 'Warrior\'s Tattoo',],
  ['Clockworks of War', 'Crag Fighting', 'Denizen of Stone', 'Dungeons Deep',
    'Escape Artist', 'Goldbergian', 'Hocus Pocus', 'Metrognome', 'Thieving Stunties',
    'Tunnel Vision', 'Underfoot', 'Wretched Prankster',],
  ['Beguiler', 'Cat-like Reflexes', 'Craven', 'Farsight', 'Fettered Chaos',
    'Fieldwarden', 'Fleet-footed', 'Hijinks', 'Kleptomania', 'Low Blow',
    'Memento', 'Pintsized'],
  ['Broad Bellied', 'Cast-Iron Stomach', 'Cruisi\'n for a Bruisin\'', 
    'Frightening Bellow', 'Gut-Plate', 'Hunger Pangs', 'Mighty Thews',
    'Odd Couple', 'Rotgut Spray', 'Slamdance', 'Thick Lining', 'Wendigo',],
];

export const profArr = [
  ['Adherent', 'Anchorite', 'Antiquarian', 'Apothecary',
    'Astrologer', 'Diabolist', 'Engineer', 'Informer',
    'Investigator', 'Monk', 'Preacher', 'Scribe',],
  ['Artisan', 'Barber Surgeon', 'Boatman', 'Camp Follower',
    'Cheapjack', 'Coachman', 'Doomsayer', 'Jailer',
    'Laborer', 'Peasant', 'Rat Catcher', 'Servant',],
  ['Beggar', 'Burglar', 'Charlatan', 'Footpad',
    'Gambler', 'Graverobber', 'Guttersnipe', 'Highwayman',
    'Prostitute', 'Smuggler', 'Vagabond', 'Vigilante',],
  ['Animal Tamer', 'Bailiff', 'Bonepicker', 'Bounty Hunter',
    'Gamekeeper', 'Hedgewise', 'Old Believer', 'Outrider',
    'Pilgrim', 'Reeve', 'Slayer', 'Trapper',],
  ['Anarchist', 'Courtier', 'Cultist', 'Entertainer',
    'Envoy', 'Fop', 'Jester', 'Provocateur',
    'Racketeer', 'Raconteur', 'Rake', 'Valet',],
  ['Berserker', 'Bravo', 'Buccaneer', 'Dragoon',
    'Hedge Knight', 'Man-At-Arms', 'Militiaman', 'Pit Fighter',
    'Pugilist', 'Sellsword', 'Squire', 'Watchman',],
];

export const trappingsArr = [
  ['Black lotus', 'Bottle of leeches', 'Coin purse', 'Dirk',
    'Fine clothing', 'Holy symbol', 'Loose robes', 'Quicksilver',
    'Royal water', 'Shoulder bag', 'Smelling salts (3)',
    'soft shoes or leather sandals', 'Writing kit',
    'Cudgel or staff or Throwing knives (3) with Bandolier',],
  ['Bandages (3)', 'Bottle bomb', 'Grave root', 'Holy symbol',
    'Leather sandals or Heavy boots', 'Ruck sack', 'Shiv',
    'Simple attire', 'Warm vest',
    'Shepherd\'s sling with sling stones (9) or Splitting maul or Threshing flail',],
  ['Antivenom', 'Dark clothes or Tattered rags', 'Folkbane (3)',
    'Gaff bag', 'Garish attire or Secondhand attire', 'Holy symbol',
    'Lock picks', 'Mantle', 'Soft shoes', 'Stiletto',
    'Blackjack or Garrote or Flintlock pistol with gunpowder & shot (6)',],
  ['Animalbane (3)', 'Antivenom', 'Backpack', 'Bullwhip',
    'Heavy boots', 'Holy symbol', 'Suit of fur/hide armor', 'Survival kit',
    'Torches (3)', 'Traveling clothes', 'Waterskin', 'Wilderness cloak',
    'Wolfsbane', 'Fire-hardened spear or Hunting bow with arrows (9) & quiver or Woodsman\'s axe',],
  ['Coin purse', 'Fancy shoes', 'Fashionable clothing', 'Foppish hat',
    'Holy symbol', 'Knuckleduster', 'Mandrake root (3)', 'Mantle',
    'Neck ruff', 'Shoulder bag', 'Writing kit', 
    'Throwing knives (3) with bandolier or Rapier or Walking cane (improvised hand weapon',],
  ['Fire-hardened spear', 'Heavy boots', 'Lantern', 'Laudanum (3)',
    'Military attire', 'Oil pot', 'Red cap mushrooms', 'Rucksack',
    'Suit of leather armor', 'Tincture (3)', 'Wooden shield',
    'Arbalest crossbow with bolts (9) & quiver or Mortuary Sword or Pike',],
];

export const buildArr = ['frail', 'slender', 'normal', 'husky', 'corpulent',];

export const alignments = {
  order: ['Adaptation', 'Ambition', 'Candor', 'Charity', 'Compassion',
    'Cunning', 'Dignity', 'Diplomacy', 'Duty', 'Enlightenment',
    'Ferocity', 'Gentility', 'Gravitas', 'Heroism', 'Humility',
    'Impiety', 'Independence', 'Mystery', 'Pride', 'Romanticism',
    'Skepticism', 'Sophistication', 'Wisdom', 'Wit', 'Zeal'],
  chaos: ['Mayhem', 'Tyranny', 'Cruelty', 'Pity', 'Melancholy',
    'Deceit', 'Vehemence', 'Hypocrisy', 'Fatalism',
    'Detachment', 'Hatred', 'Cowardice', 'Vanity', 'Martyrdom',
    'Incompetence', 'Heresy', 'Rebellion', 'Exclusion', 'Arrogance',
    'Lechery', 'Cynicism', 'Indulgence', 'Rancor', 'Scorn', 'Fanaticism'],
};

export const markArr = ['Abnormally white teeth', 'Abundance of freckles on face',
  'Acne-scarred face', 'Additional toes or fingers', 'Almond-shaped eyes',
  'Asexual appearance', 'Ashy elbows', 'Balding pate', 'Beaded mustachio',
  'Beady eyes', 'Beauty mark on face', 'Big ears', 'Blood-shot eyes',
  'Bow-legged walk', 'Branded with cattle iron', 'Broken nose',
  'Buck-toothed or snaggle-toothed', 'Bulging eyes', 'Burn scars on face and arms',
  'Bushy eyebrows', 'Carefully-groomed beard', 'Cherubic face', 'Clammy hands',
  'Claw marks over face', 'Covered in black moles', 'Curly locks of hair',
  'Devilish goatee', 'Different colored eyes', 'Dimpled cheeks', 'Doll-like face',
  'Drooping eye', 'Dry, flaking skin', 'Ear half-missing', 'Embarrassing acne scars',
  'Embarrassing tattoo on face', 'Excessive body hair', 'Eyes too far apart',
  'False finger', 'Farmer\'s tan', 'Glasgow grin', 'Golden lock of hair',
  'Hare lip', 'Hooked nose', 'Horse-faced', 'Humpbacked', 'Incredibly beautiful',
  'Itchy scabies bites', 'Jaundiced complexion', 'Lanky hair', 'Large and hairy mole',
  'Large nose', 'Large red birthmark on arms', 'Lazy eye', 'Leathery countenance',
  'Lichtenberg scar', 'Long eyelashes', 'Long mustachio', 'Long sideburns',
  'Milky eye', 'Mismatched eye color', 'Missing an eyebrow', 'Missing fingers',
  'Nervous tic', 'Older-looking face', 'Painted beard', 'Pallid countenance',
  'Patch of white hair', 'Perfect posture', 'Perpetual sneer',
  'Perpetually deep frown', 'Piercing eyes', 'Pigeon-toed stance', 'Pot belly',
  'Pox scars all over body', 'Pronounced brow', 'Purple bags beneath eyes',
  'Rancid breath', 'Rash of pimples', 'Rheumy eyes', 'Six-fingered hand',
  'Slouchy posture', 'Spiked mohawk', 'Squinting eyes or false eye patch',
  'Steely gaze', 'Strong jaw', 'Sunburn scars', 'Sunken eyes', 'Tanned, leathery skin',
  'Tarred and feathered', 'Terribly crooked teeth', 'Vacant expression',
  'Veteran\'s nose', 'Vulgar tattoo', 'Weak chin', 'Wears spectacles',
  'Webbed hands and feet', 'Widow\'s peak', 'Wind-chapped lips',
  'Yellow scum on teeth', 'Yellowed fingernails and toenails'];

export const complexionArr = ['Pale', 'Fair', 'Light', 'Light tan', 'Tan', 'Dark tan',
  'Light brown', 'Brown', 'Dark brown', 'Ebony',];

export const seasonArr = ['Spring', 'Summer', 'Autumn', 'Winter',];

export const ancestryArr = ['Dwarf', 'Elf', 'Gnome', 'Halfling', 'Ogre',];

export const doomingArr = [
  ['Pride comes before a fall', 'Ivy will claw at your skin and prick like a rose',
    'Health is not always healthy', 'Still waters run deep',
    'The forest will strike back when the campfire is low',
    'Do not pluck low-hanging fruit', 'The serpent is in the garden',
    'Climb not the mighty oak', 'Beware fairy rings and standing stones',
    'The land will reclaim what is hers', 'Do not stare directly into the light',
    'Good intentions create bad situations', 'Do not accept trust lightly',
    'There is always another problem', 'Light burns just as much as it heals',
    'Radiance can’t illuminate all', 'Charity will cause your end',
    'Underestimate no one', 'Birth is but the start of death',
    'Provide no succor to the blind man', 'Do not pick up discarded coins',
    'Twice for poison, thrice for a kiss', 'Fate is cruel, but ironic',
    'A trick is not an illusion', 'You will be stabbed by your own knife',],
  ['Your end will be at the head of a hammer', 'You will see your own hubris and end your life',
    'Those you love will kill you', 'Beware the comet’s warning',
    'They will come as twins and leave as triplets', 'You will die trying to save someone you love',
    'Beware a lover scorned', 'You will witness the end, then go into it',
    'The heathen will cut you down', 'Your final moments will be full of divine pain',
    'Your flame shall consume you', 'Mercy will be your downfall',
    'You will burn brightly, then be snuffed out', 'The unlit path is the most dangerous',
    'Iron will bend under heat', 'Respect power, for it does not respect you',
    'Never leave a fire burning', 'Never turn your back on a foe',
    'Your embers shall smolder', 'The sun can be a cruel friend',
    'Death comes from above and below', 'Lightning sometimes does strike twice',
    'A squall occurs before a storm', 'The eye of a storm is just a reprieve',
    'The heavens will open, angry and bright',],
  ['A murder of another will herald thine death', 'Thy skin shall darken as if soaked in ink',
    'Do not cross a freshly dug tomb', 'You shall see thine death twice',
    'Up from the canyon, soars the raven', 'Sorrow will fill your heart at death',
    'You shall not see the end', 'One step forward, two steps back',
    'The jackdaw is a false omen', 'A visage will haunt you to your grave',
    'The Eye will look upon you with scorn', 'You will die in a pool of blood, but it will not be yours',
    'Your end will not be clean', 'Sickness will be your downfall',
    'The stench of the grave follows you', 'New beginnings herald sudden ends',
    'The Abyss also gazes back', 'The shadows stalk hungrily',
    'Three flies bring your doom', 'Beware the black stallion',
    'Do not fold, always stay', 'Confusion will kill more than you',
    'Do not be fooled by appearances', 'Avoid the exotic when possible',
    'Do not push for more, as you will get it',],
  ['Beware the toothless hound', 'Warm winters bring hard frost',
    'Do not trust what you can’t see', 'Blood will be upon your hands',
    'The oldest are the strongest', 'Be wary of false friends',
    'Numbers overwhelm might', 'Your killer will not know your name',
    'At times, being found is worse than being lost',
    'Do not tread upon thick ice nor thin', 'Iron is weak, gold is strong',
    'Your left eye will not see the truth', 'Revenge is upon you',
    'Absolute power corrupts absolutely', 'Being immovable is not always a boon',
    'Some things, man should not know', 'Justice is blind, deaf and dumb',
    'Six of one, half a dozen of the other', 'Fear change, as it changes you',
    'The gavel will ring twice', 'The stars can lead you astray',
    'The depths are crushing, the shallows inviting', 'From the cold, something eyes you hungrily',
    'You, too can be touched by the unknown', 'Do not fly too close to the stars',],
];

export const hairColors = {
  dwarfGnomeOgre: ['Medium brown', 'Dark brown', 'Light brown', 'Jet black',
                    'Grey', 'Chestnut', 'Ginger', 'Sienna', 'Corn yellow',
                    'Ash blonde', 'Salt & pepper', 'Silver', 'White',
                    'Red', 'Blue-black', 'Black'],
  elf: ['Honey brown', 'Golden brown', 'Straw yellow', 'golden yellow',
        'Chestnut', 'Copper', 'Ginger', 'Ash blonde', 'Sienna',
        'Silver', 'Smokey grey', 'Ivory white', 'Blue-black',
        'Jet black', 'Fiery red', 'Black'],
  halfling: ['Dark brown', 'Medium brown', 'Light brown', 'Sienna',
              'Red', 'Fiery red', 'Black', 'Blue black', 'Ginger',
              'Corn yellow', 'Chestnut', 'Ash blonde', 'Salt & pepper',
              'Grey', 'White', 'Silver'],
  human: ['Medium brown', 'Dark brown', 'Light brown', 'Sienna',
          'Black', 'Ash blonde', 'Chestnut', 'Ginger', 'Corn yellow',
          'Red', 'Salt & pepper', 'Blue black', 'Grey', 'Silver',
          'White', 'Jet black'],
};

export const eyeColors = {
  dwarf: ['Dark brown', 'Grey', 'Black', 'Medium brown', 'Grey blue',
          'Light brown', 'Hazel', 'Pale green', 'Blue', 'Copper',
          'Dark green', 'Green', 'Ice blue', 'Violet'],
  elf: ['Amber', 'Silver', 'Honey', 'Emerald', 'Molasses',
        'Crystal blue', 'Hazel', 'Black', 'Sapphire', 'Copper',
        'Blue purple', 'Gold', 'Silver green', 'Violet'],
  gnome: ['Dark brown', 'Grey', 'Medium brown', 'Hazel', 'Black',
          'Light brown', 'Grey blue', 'Pale green', 'Dark green',
          'Blue', 'Copper', 'Ice blue', 'Green', 'Violet'],
  halfling: ['Hazel', 'Light brown', 'Medium brown', 'Grey',
              'Dark brown', 'Pale green', 'Copper', 'Green', 'Black',
              'Grey blue', 'Blue', 'Dark green', 'Ice blue', 'Violet'],
  human: ['Dark brown', 'Grey', 'Medium brown', 'Hazel', 'Black',
          'Light brown', 'Grey blue', 'Pale green', 'Dark green',
          'Blue', 'Copper', 'Ice blue', 'Green', 'Violet'],
  ogre: ['Hazel', 'Light brown', 'Medium brown', 'Grey', 'Dark brown',
          'Pale green', 'Copper', 'Green', 'Black', 'Grey blue',
          'Blue', 'Dark green', 'Ice blue', 'Violet'],
};